### ISSUE TITLE
Not available all regions in entering an account details

### ISSUE THREAD

**Issue by YuliaKovalenko** [SmartBear/ready-aws-plugin#2]
In deploy API to AWS API Gateway  in entering an account details user can't select current region (for example EU-WEST)

Additional info:
Ready! API 1.8.0 © SmartBear Inc. 2007-2016
![region](https://cloud.githubusercontent.com/assets/12726938/17704029/5913f6e2-63dc-11e6-84b5-c3d1c9fd5584.JPG)

**Comment by olensmar** [comment]
Hi Yulia - I've deployed version 1.0.1 of the plugin - hopefully that fixes the issue - please let me know otherwise

/Ole

**Comment by deanpeterson** [comment]
@olensmar  US East 2 (Ohio) is not available. That is actually the only region we are allowed to use and that is not available in the drop down.
