### ISSUE TITLE
Region Dropdown not showing all available regions

### ISSUE THREAD

**Issue by ECiurleo** [SmartBear/ready-aws-plugin#3]
Region Dropdown not showing all available regions

![soapui](https://cloud.githubusercontent.com/assets/10923417/17704033/9827946c-63cb-11e6-9746-148606fc8635.PNG)

The full list of regions is contained in AccountInfoDialog

```
//map of the all available regions, https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/?nc1=h_ls
    private static Map<String, String> regions = new HashMap<String, String>() {{
        put("US East (N. Virginia)", "us-east-1");
        put("US West (Oregon)", "us-west-2");
        put("US West (N. California)", "us-west-1");
        put("South America (Sao Paulo)", "sa-east-1");
        put("EU (Ireland)", "eu-west-1");
        put("EU (Frankfurt)", "eu-central-1");
        put("Asia Pacific (Tokyo)", "ap-northeast-1");
        put("Asia Pacific (Singapore)", "ap-southeast-1");
        put("Asia Pacific (Sydney)", "ap-southeast-2");
    }};
```

ReadyAPI version - 1.8.0
Plugin version - 1.0

**Comment by ECiurleo** [comment]
had a quick look, the list is easy to fix,

> ```
>    //see available regions at the http://docs.aws.amazon.com/general/latest/gr/rande.html
>     @AField(name = Strings.AccountInfoDialog.REGION_LABEL, description = Strings.AccountInfoDialog.REGION_DESCRIPTION, type = AField.AFieldType.COMBOBOX,
>             values = {"US East (N. Virginia)", "US West (Oregon)", "US West (N. California)", "South America (Sao Paulo)", "EU (Ireland)", "EU (Frankfurt)", "Asia Pacific (Tokyo)", "Asia Pacific (Singapore)", "Asia Pacific (Sydney)"}, defaultValue = "US East (N. Virginia)")
>     public final static String REGION = Strings.AccountInfoDialog.REGION_LABEL;
> }
> ```

added into AccountInfoDialog.java

Leads me cleanly to the next error where the service cant download the APIs....
The ApiListLoader.java calls the ApiOperationBase to find its endpoint locations. I think these are wrong but not been able to quickly find the correct endpoints. As its set atm it is;

> APIS_PATH = "/restapis";

**Comment by olensmar** [comment]
Thanks - I'll look into this!

**Comment by olensmar** [comment]
i've added a PR for the missing regions - https://github.com/SmartBear/ready-aws-plugin/pull/4

the endpoint looks right to me - http://docs.aws.amazon.com/apigateway/api-reference/resource/rest-apis/ !?

**Comment by ECiurleo** [comment]
Apologies that was a misdiagnosis by myself, the list seems all present!  Thanks for your help

**Comment by olensmar** [comment]
ok thanks - i'll get this merged and will update the plugin over the weekend!
